version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - '8080:80'
    volumes:
      - ./${NGINX_DEFAULT_CONF}:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    networks:
      - default
      - napspans_network

networks:
  napspans_network:
    external: true